# Generated by Django 4.1.7 on 2023-03-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='bugs',
            field=models.ManyToManyField(to='main_app.bug'),
        ),
    ]
